name: 'Bump Ruby Gem'
description: 'Updates a Ruby gem using bundler and opens a pull request with the changes'
branding:
  icon: 'arrow-up-circle'
  color: 'red'

inputs:
  gem_name:
    description: 'Name of the Ruby gem to update'
    required: true
  github_token:
    description: 'GitHub token for creating pull requests'
    required: true
  branch_name:
    description: 'Name of the branch to create for the PR'
    required: false
    default: ''
  labels:
    description: 'Comma-separated list of labels to apply to the pull request'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up branch name
      id: branch
      shell: bash
      run: |
        if [ -n "${{ inputs.branch_name }}" ]; then
          echo "name=${{ inputs.branch_name }}" >> $GITHUB_OUTPUT
        else
          echo "name=bump-${{ inputs.gem_name }}-$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
        fi

    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true

    - name: Ensure jq is installed
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          echo "jq not found, installing..."
          sudo apt-get update
          sudo apt-get install -y jq
        fi

    - name: Get old version
      id: old_version
      shell: bash
      run: |
        # Extract the old version from Gemfile.lock before updating
        OLD_VERSION=$(grep -E "^\s+${{ inputs.gem_name }} \(" Gemfile.lock | head -1 | sed 's/.*(\(.*\))/\1/')
        if [ -n "$OLD_VERSION" ]; then
          echo "version=$OLD_VERSION" >> $GITHUB_OUTPUT
          echo "Found old version: $OLD_VERSION"
        else
          echo "Could not find old version for ${{ inputs.gem_name }}"
          echo "version=" >> $GITHUB_OUTPUT
        fi

    - name: Update gem with bundler
      shell: bash
      env:
        BUNDLE_FROZEN: false
      run: |
        bundle update --conservative ${{ inputs.gem_name }}

    - name: Get changelog URL
      id: changelog
      shell: bash
      run: |
        # Extract the new version from Gemfile.lock (handles various indentation)
        VERSION=$(grep -E "^\s+${{ inputs.gem_name }} \(" Gemfile.lock | head -1 | sed 's/.*(\(.*\))/\1/')
        if [ -z "$VERSION" ]; then
          echo "Could not find version for ${{ inputs.gem_name }}"
          echo "url=" >> $GITHUB_OUTPUT
          echo "new_version=" >> $GITHUB_OUTPUT
          echo "github_repo=" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "Found version: $VERSION"
        echo "new_version=$VERSION" >> $GITHUB_OUTPUT

        # Fetch gem info from RubyGems API
        API_URL="https://rubygems.org/api/v2/rubygems/${{ inputs.gem_name }}/versions/${VERSION}.json"
        RESPONSE=$(curl -sf "$API_URL" 2>/dev/null) || {
          echo "Failed to fetch gem info from RubyGems API"
          echo "url=" >> $GITHUB_OUTPUT
          echo "github_repo=" >> $GITHUB_OUTPUT
          exit 0
        }

        CHANGELOG_URL=$(echo "$RESPONSE" | jq -r '.changelog_uri // empty')
        SOURCE_CODE_URI=$(echo "$RESPONSE" | jq -r '.source_code_uri // empty')
        HOMEPAGE_URI=$(echo "$RESPONSE" | jq -r '.homepage_uri // empty')

        if [ -n "$CHANGELOG_URL" ]; then
          echo "url=$CHANGELOG_URL" >> $GITHUB_OUTPUT
          echo "Found changelog: $CHANGELOG_URL"
        else
          echo "No changelog URL found"
          echo "url=" >> $GITHUB_OUTPUT
        fi

        # Extract GitHub repo - try source_code_uri first, fall back to homepage_uri
        REPO_URI=""
        if [ -n "$SOURCE_CODE_URI" ]; then
          echo "Found source code URI: $SOURCE_CODE_URI"
          REPO_URI="$SOURCE_CODE_URI"
        elif [ -n "$HOMEPAGE_URI" ]; then
          echo "No source code URI, trying homepage URI: $HOMEPAGE_URI"
          REPO_URI="$HOMEPAGE_URI"
        fi

        if [ -n "$REPO_URI" ]; then
          # Check if it's a GitHub URL and extract owner/repo
          if echo "$REPO_URI" | grep -qE '^https://github\.com/[^/]+/[^/]+'; then
            # Extract the base GitHub repo URL (remove any trailing paths like /tree/main)
            GITHUB_REPO_URL=$(echo "$REPO_URI" | sed -E 's#^(https://github\.com/[^/]+/[^/]+).*#\1#')
            echo "github_repo=$GITHUB_REPO_URL" >> $GITHUB_OUTPUT
            echo "Found GitHub repo: $GITHUB_REPO_URL"
          else
            echo "URI is not hosted on GitHub: $REPO_URI"
            echo "github_repo=" >> $GITHUB_OUTPUT
          fi
        else
          echo "No source code URI or homepage URI found"
          echo "github_repo=" >> $GITHUB_OUTPUT
        fi

    - name: Get release links
      id: releases
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        OLD_VERSION="${{ steps.old_version.outputs.version }}"
        NEW_VERSION="${{ steps.changelog.outputs.new_version }}"
        GITHUB_REPO="${{ steps.changelog.outputs.github_repo }}"

        if [ -z "$GITHUB_REPO" ] || [ -z "$OLD_VERSION" ] || [ -z "$NEW_VERSION" ]; then
          echo "Missing required information for release links"
          echo "releases=" >> $GITHUB_OUTPUT
          exit 0
        fi

        if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
          echo "Version unchanged, no releases to list"
          echo "releases=" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Extract owner/repo from GitHub URL
        OWNER_REPO=$(echo "$GITHUB_REPO" | sed -E 's#^https://github\.com/##')
        echo "Fetching releases for $OWNER_REPO between $OLD_VERSION and $NEW_VERSION"

        # Fetch releases from GitHub API
        RELEASES_JSON=$(curl -sf -H "Authorization: token $GH_TOKEN" \
          "https://api.github.com/repos/${OWNER_REPO}/releases?per_page=100" 2>/dev/null) || {
          echo "Failed to fetch releases from GitHub API"
          echo "releases=" >> $GITHUB_OUTPUT
          exit 0
        }

        # Parse releases and filter those between old and new version
        RELEASE_LINKS=""
        while IFS= read -r line; do
          TAG=$(echo "$line" | cut -d'|' -f1)
          URL=$(echo "$line" | cut -d'|' -f2)

          # Extract version from tag (strip leading 'v' for comparison)
          TAG_VERSION=$(echo "$TAG" | sed 's/^v//')
          OLD_V=$(echo "$OLD_VERSION" | sed 's/^v//')
          NEW_V=$(echo "$NEW_VERSION" | sed 's/^v//')

          # Check if version is > old and <= new
          if [ "$(printf '%s\n%s' "$OLD_V" "$TAG_VERSION" | sort -V | head -n1)" = "$OLD_V" ] && \
             [ "$OLD_V" != "$TAG_VERSION" ] && \
             [ "$(printf '%s\n%s' "$TAG_VERSION" "$NEW_V" | sort -V | head -n1)" = "$TAG_VERSION" ]; then
            if [ -n "$RELEASE_LINKS" ]; then
              RELEASE_LINKS="${RELEASE_LINKS}
        - [$TAG]($URL)"
            else
              RELEASE_LINKS="- [$TAG]($URL)"
            fi
          fi
        done < <(echo "$RELEASES_JSON" | jq -r '.[] | "\(.tag_name)|\(.html_url)"')

        if [ -n "$RELEASE_LINKS" ]; then
          echo "releases<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_LINKS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Found releases:"
          echo "$RELEASE_LINKS"
        else
          echo "No matching releases found"
          echo "releases=" >> $GITHUB_OUTPUT
        fi

    - name: Build PR body
      id: body
      shell: bash
      run: |
        BODY="This PR updates the \`${{ inputs.gem_name }}\` gem using \`bundle update --conservative\`."
        if [ -n "${{ steps.changelog.outputs.url }}" ]; then
          BODY="${BODY}

        **Changelog:** ${{ steps.changelog.outputs.url }}"
        fi
        if [ -n "${{ steps.releases.outputs.releases }}" ]; then
          BODY="${BODY}

        **Releases:**
        ${{ steps.releases.outputs.releases }}"
        fi
        echo "content<<EOF" >> $GITHUB_OUTPUT
        echo "$BODY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Build PR title
      id: title
      shell: bash
      run: |
        OLD_VERSION="${{ steps.old_version.outputs.version }}"
        NEW_VERSION="${{ steps.changelog.outputs.new_version }}"
        if [ -n "$OLD_VERSION" ] && [ -n "$NEW_VERSION" ] && [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
          TITLE="Bump ${{ inputs.gem_name }} from $OLD_VERSION to $NEW_VERSION"
        else
          TITLE="Bump ${{ inputs.gem_name }}"
        fi
        echo "content=$TITLE" >> $GITHUB_OUTPUT

    - name: Exclude irrelevant files from the pull request
      shell: bash
      run: |
        git checkout .bundle/config || rm .bundle/config
        rm -rf vendor/bundle

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.github_token }}
        commit-message: ${{ steps.title.outputs.content }}
        title: ${{ steps.title.outputs.content }}
        body: ${{ steps.body.outputs.content }}
        branch: ${{ steps.branch.outputs.name }}
        labels: ${{ inputs.labels }}
        delete-branch: true

    - name: Show Pull Request URL
      if: steps.create-pr.outputs.pull-request-url
      shell: bash
      run: |
        echo "::notice::Pull request created: ${{ steps.create-pr.outputs.pull-request-url }}"
