name: 'Bump Ruby Gem'
description: 'Updates a Ruby gem using bundler and opens a pull request with the changes'
branding:
  icon: 'arrow-up-circle'
  color: 'red'

inputs:
  gem_name:
    description: 'Name of the Ruby gem to update'
    required: true
  github_token:
    description: 'GitHub token for creating pull requests'
    required: true
  branch_name:
    description: 'Name of the branch to create for the PR'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up branch name
      id: branch
      shell: bash
      run: |
        if [ -n "${{ inputs.branch_name }}" ]; then
          echo "name=${{ inputs.branch_name }}" >> $GITHUB_OUTPUT
        else
          echo "name=bump-${{ inputs.gem_name }}-$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
        fi

    - name: Update gem with bundler
      shell: bash
      run: bundle update --conservative ${{ inputs.gem_name }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.github_token }}
        commit-message: "Bump ${{ inputs.gem_name }}"
        title: "Bump ${{ inputs.gem_name }}"
        body: |
          This PR updates the `${{ inputs.gem_name }}` gem using `bundle update --conservative`.

          ---
          *Created by [bump](https://github.com/dentarg/bump)*
        branch: ${{ steps.branch.outputs.name }}
        delete-branch: true
